FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip build-essential curl gcc g++ make python3-dev patchelf && \
    pip3 install --upgrade pip setuptools wheel nuitka zstandard python-dotenv cryptography requests openai

WORKDIR /src

CMD ["bash"]
