FROM redhat/ubi8:latest

# Instala epel-release y utilidades básicas, Python y herramientas de desarrollo
RUN yum install -y epel-release && \
	yum install -y wget curl unzip python3 python3-pip gcc gcc-c++ make python3-devel patchelf

RUN pip3 install --upgrade pip setuptools wheel nuitka

CMD ["/bin/bash"]
