FROM redhat/ubi8:latest

# Instala utilidades básicas, Python y herramientas de desarrollo
RUN yum install -y wget curl unzip python3 python3-pip gcc gcc-c++ make python3-devel bzip2

# Instala patchelf manualmente
RUN wget https://github.com/NixOS/patchelf/releases/download/0.17.2/patchelf-0.17.2.tar.bz2 && \
	tar -xjf patchelf-0.17.2.tar.bz2 && \
	cd patchelf-0.17.2 && \
	./configure && make && make install && \
	cd .. && rm -rf patchelf-0.17.2 patchelf-0.17.2.tar.bz2

RUN pip3 install --upgrade pip setuptools wheel nuitka zstandard python-dotenv cryptography requests openai

CMD ["/bin/bash"]
