name: Build Agent Binario y Publicar Release

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: 'Dockerfile a usar (ej: Dockerfile.ubi8, Dockerfile.ubuntu, Dockerfile.centos)'
        required: true
        default: 'Dockerfile.ubi8'
      release_tag:
        description: 'Tag para el release (ej: v1.0.0-ubi8)'
        required: true
        default: 'v1.0.0-ubi8'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: agente

      - name: Debug lista archivos en workspace/agente
        run: ls -l ${{ github.workspace }}/agente

      - name: Debug busca build_agent.sh en todo el workspace
        run: find ${{ github.workspace }} -name build_agent.sh

      - name: Build Docker image
        run: docker build -f ${{ github.workspace }}/agente/dockerfiles/${{ github.event.inputs.dockerfile }} -t agent-build ${{ github.workspace }}/agente

      - name: lista archivos en /src
        run: docker run --rm -v ${{ github.workspace }}/agente:/src agent-build bash -c "ls -l /src"

      - name: Build agent in Docker
        run: docker run --rm -v ${{ github.workspace }}/agente:/src agent-build bash -c "cd /src && chmod +x build_agent.sh && ./build_agent.sh"

      - name: Upload binario como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: agent-${{ github.event.inputs.dockerfile }}
          path: agente/dist/agent

      - name: Publicar binario en GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: "Agent Binario ${{ matrix.dockerfile }}"
          files: agente/dist/agent
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Actualiza releases.md
        run: |
          python agente/update_releases_md.py "${{ github.event.inputs.release_tag }}" "${{ github.event.inputs.dockerfile }}" "${{ github.event.inputs.dockerfile }}" "https://github.com/v4mpir0ck/agent-linux/releases/tag/${{ github.event.inputs.release_tag }}"
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add README-releases.md
          git commit -m "docs: actualiza README-releases.md con release ${{ github.event.inputs.release_tag }}"
          git push