name: Build Agent Binario y Publicar Release

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: 'Dockerfile a usar (ej: Dockerfile.ubi8, Dockerfile.ubuntu, Dockerfile.centos)'
        required: true
        default: 'Dockerfile.ubi8'
      release_tag:
        description: 'Tag para el release (ej: v1.0.0-ubi8)'
        required: true
        default: 'v1.0.0-ubi8'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build agent in Docker
        run: |
          docker build -f dockerfiles/${{ github.event.inputs.dockerfile }} -t agent-build .
          docker run --rm -v ${{ github.workspace }}/agente:/src agent-build bash /src/build_agent.sh

      - name: Upload binario como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: agent-${{ github.event.inputs.dockerfile }}
          path: agente/dist/agent

      - name: Publicar binario en GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: "Agent Binario ${{ matrix.dockerfile }}"
          files: agente/dist/agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
